# Generated by Django 2.0.10 on 2019-02-27 08:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=(5, '5'), help_text='Must be a number 1 through 5', validators=[django.core.validators.MaxValueValidator(limit_value=5)], verbose_name='Rating')),
                ('title', models.CharField(help_text='No more than 64 chars', max_length=64, unique=True, validators=[django.core.validators.MaxLengthValidator(limit_value=64)], verbose_name='Title')),
                ('summary', models.TextField(help_text='No more than 10k chars', max_length=10000, validators=[django.core.validators.MaxLengthValidator(limit_value=10000)], verbose_name='Summary')),
                ('date_submitted', models.DateTimeField(default=django.utils.timezone.now, help_text='The date the review was submitted', verbose_name='Date Submitted')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
            ],
        ),
    ]
